import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";
import BottomNav from "@/components/BottomNav";
import AuthProvider from "../context/AuthContext";

import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className="bg-[#fafafa] min-h-screen flex justify-center">
        <div className="w-full max-w-[430px] min-h-screen relative bg-white">
          <Header />
          <main className="pt-[60px] pb-[70px]">{children}</main>
          <BottomNav />
        </div>
      </body>
    </html>
  );
}
